FORMAT: 1A

# Doku Shop API

Doku Shop API adalah sebuah API sederhana untuk aplikasi android Doku Shop

## Koleksi Merek [/merek]

Ini menyangkut seluruh merek dan model HP

### Daftar Semua Merek [GET]

Mengembalikan daftar merek dan daftar model dari setiap merek

+ Response 200 (application/json)

        [
            {
                "nama_merek": "Apple",
                "model": []
            },
            {
                "nama_merek": "Asus",
                "model": ["Nexus 7"]
            },
            {
                "nama_merek": "Blackberry",
                "model": []
            },
            {
                "nama_merek": "HTC",
                "model": []
            },
            {
                "nama_merek": "Huawei",
                "model": ["Ascend D1"]
            },
            {
                "nama_merek": "Lenovo",
                "model": []
            },
            {
                "nama_merek": "LG",
                "model": []
            },
            {
                "nama_merek": "Nokia",
                "model": []
            },
            {
                "nama_merek": "Oppo",
                "model": []
            },
            {
                "nama_merek": "Sony",
                "model": ["XPeria Z"]
            }
        ]

## Koleksi Aksesoris [/aksesoris]

### Daftar Semua Aksesoris [GET /aksesoris/{nama_merek}/{model}]

Mengembalikan aksesoris untuk merek dan model tertentu. Di dalamnya termasuk id_aksesoris dan image_path. id_aksesoris digunakan untuk mengakses apa saja pilihan untuk aksesoris tersebut. image_path digunakan untuk mengakses gambar.

+ Parameters
    + nama_merek: 'Sony' - Merk HP
    + model: 'XPeria Z' - model HP

+ Response 200 (application/json)

        [
            {
                "id_aksesoris": 1,
                "nama_aksesoris": "Nillkin Crossed Style Leather Case",
                "harga": 190000,
                "image_path": "/image/aksesoris/Sony/XPeria Z/1.png"
                
            },
            {
                "id_aksesoris": 2,
                "nama_aksesoris": "Nillkin Easy Series Leather Case",
                "harga": 180000,
                "image_path": "image/aksesoris/Sony/XPeria Z/2.png"
            },
            {
                "id_aksesoris": 3,
                "nama_aksesoris": "Nillkin Fresh Series Leather Case",
                "harga": 150000,
                "image_path": "image/aksesoris/Sony/XPeria Z/3.png"
            },
            {
                "id_aksesoris": 4,
                "nama_aksesoris": "Nillkin Hardcase",
                "harga": 135000,
                "image_path": "image/aksesoris/Sony/XPeria Z/4.png"
            }
        ]


### Daftar Pilihan [GET /aksesoris/{nama_merek}/{model}/{id}/pilihan]

Mengembalikan daftar pilihan aksesoris dengan id tertentu

+ Parameters
    + nama_merek: Sony - Merk HP
    + model: XPeria Z - model HP
    + id: 1 - ID aksesoris

+ Response 200 (application/json)

        [
            "purple"
        ]

+ Response 404

##Koleksi Image [/image]
### Gambar [GET /image/aksesoris/{nama_merek}/{model}/{nama_file}]

Mengembalikan gambar. URI di atas seharusnya sesuai dengan image_path yang diberikan dari koleksi aksesoris

+ Parameters
    + nama_merek: Sony - Merk HP
    + model: XPeria Z - model HP
    + nama_file: 1.png - ID aksesoris

+ Response 200 (image/{jpg/png})